version: 0.2

env:
  secrets-manager:
    SSH_PRIVATE_KEY_B64: codebuild-ec2-ssh-key-b64:SSH_PRIVATE_KEY_B64

phases:
  install:
    commands:
      - yum install -y openssh-clients
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -lf ~/.ssh/id_rsa

  build:
    commands:
      - mvn clean package -DskipTests

  post_build:
    commands:
      # Ensure app directory exists
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@65.2.141.219 "mkdir -p /home/ec2-user/app"

      # Copy new JAR
      - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no target/*.jar ec2-user@65.2.141.219:/home/ec2-user/app/

      # Stop old app safely using PID (NO pkill)
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@65.2.141.219 \
        "if [ -f /home/ec2-user/app/app.pid ]; then kill $(cat /home/ec2-user/app/app.pid) || true; fi"

      # Start app and store new PID
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@65.2.141.219 \
        "cd /home/ec2-user/app && nohup java -jar *.jar > app.log 2>&1 & echo $! > app.pid"

artifacts:
  files:
    - target/*.jar
