version: 0.2

env:
  secrets-manager:
    SSH_PRIVATE_KEY_B64: codebuild-ec2-ssh-key-b64:SSH_PRIVATE_KEY_B64

phases:
  install:
    commands:
      - yum install -y openssh-clients
      - mkdir -p ~/.ssh
      - echo "$SSH_PRIVATE_KEY_B64" | base64 -d > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - ssh-keygen -lf ~/.ssh/id_rsa

  build:
    commands:
      - mvn clean package -DskipTests

  post_build:
    commands:
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@43.205.119.20 "mkdir -p /home/ec2-user/app"
      - scp -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no target/*.jar ec2-user@43.205.119.20:/home/ec2-user/app/
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@43.205.119.20 "pkill -f java || true"
      - ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no ec2-user@43.205.119.20 "nohup java -jar /home/ec2-user/app/*.jar > app.log 2>&1 &"

artifacts:
  files:
    - target/*.jar
