version: 0.2

env:
  secrets-manager:
    SSH_PRIVATE_KEY: codebuild-ec2-ssh-key:SSH_PRIVATE_KEY

phases:
  install:
    commands:
      - yum install -y openssh-clients
      - mkdir -p ~/.ssh
      - printf "%s\n" "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa

  build:
    commands:
      - mvn clean package -DskipTests

  post_build:
    commands:
      - ssh -o StrictHostKeyChecking=no ec2-user@43.205.119.20 "mkdir -p /home/ec2-user/app"
      - scp -o StrictHostKeyChecking=no target/*.jar ec2-user@43.205.119.20:/home/ec2-user/app/
      - ssh -o StrictHostKeyChecking=no ec2-user@43.205.119.20 "pkill -f java || true"
      - ssh -o StrictHostKeyChecking=no ec2-user@43.205.119.20 "nohup java -jar /home/ec2-user/app/*.jar > app.log 2>&1 &"

artifacts:
  files:
    - target/*.jar
